### ISSUE TITLE
Examples ?

### ISSUE THREAD

**Issue by ghost** [kranfix/dart-nats#1]
I also use NATS and was considering how useful it would be with a dart client and then used with RX.

I am Keen to help. Do you have a flutter example ising it with RX yet ?

I wrote a golang plugins for flutter so I can have a nats client inside flutter. It's using json to serialise the code between golang and flutter.

**Comment by ghost** [comment]
I got NATS working as a flutter plugin so I can let all GUI controls do choreography now.

The agreement on the domain model the flutter GUI controls all use it in a state of design flux ( bad pun :) ).

Also I am guessing you using this to talk directly to a NATS server.
I think it's the wrong way.
When things start to scale out you want a hub and spoke pattern of NATS.

So local NATS handles all your flutter widget pub sub and also handles talking to the hub NATS server.
It's basically turtles all the way down design pattern. Or Russian dolls . Or if your into parametric generative design you would say it's fractal because it exhibits self similarity !

**Comment by kranfix** [comment]
Hello. It is a work in progress. In this moment it is on standby, but it
will resumed soon.
